# Generated by Django 3.2.10 on 2022-01-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineinfo',
            name='value',
            field=models.IntegerField(),
        ),
    ]
