FROM python:3.7.2

RUN mkdir /code
WORKDIR /code

ADD . /code

RUN pip install uwsgi
RUN pip config set global.index-url http://mirrors.aliyun.com/pypi/simple
RUN pip config set install.trusted-host mirrors.aliyun.com
RUN pip install -r requirements.txt
#RUN python manage.py collectstatic -y
RUN python manage.py makemigrations
RUN python manage.py migrate







